# .github/workflows/scrape-calendar.yml

name: Scrape Calendar (every 24h)

on:
  schedule:
    - cron: '0 0 * * *'  # täglich um 00:00 UTC

jobs:
  trigger-scrape-calendar:
    runs-on: ubuntu-latest
    steps:
      - name: Ping /api/cron/scrape-calendar
        run: |
          curl -sSf \
            -H "x-api-key: ${{ secrets.X_API_KEY }}" \
            "${{ secrets.API_BASE_URL }}/api/cron/scrape-calendar"