# .github/workflows/scrape-library.yml

name: Scrape Library (alle 10 Minuten)

on:
  schedule:
    - cron: '*/10 * * * *'  # alle 10 Minuten (UTC)

jobs:
  trigger-scrape-library:
    runs-on: ubuntu-latest
    steps:
      - name: Ping /api/cron/scrape-library
        run: |
          curl -sSf \
            -H "x-api-key: ${{ secrets.X_API_KEY }}" \
            "${{ secrets.API_BASE_URL }}/api/cron/scrape-library"