import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from 'next-themes';
import NProgressBar from '@/components/NProgressBar';
import { AnalyticsProvider, GoogleAnalyticsScript, CookieBanner } from '@/lib/analytics';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
            <head>
                <link rel="manifest" href="/app/manifest.ts" />
                <meta name="theme-color" content="#4f46e5" />
                {/* Apple-PWA Unterstützung */}
                <meta name="apple-mobile-web-app-capable" content="yes" />
                <meta name="apple-mobile-web-app-status-bar-style" content="default" />
                <link rel="apple-touch-icon" href="/icons/icon-192.png" />
            </head>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased `}>
                <GoogleAnalyticsScript />
                <ThemeProvider attribute="class" defaultTheme="light" enableSystem={false}>
                    <AnalyticsProvider>
                        <NProgressBar />
                        {children}
                        <CookieBanner />
                    </AnalyticsProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
