import type { Metadata } from 'next';
import './globals.css';

import { MantineProvider } from '@mantine/core';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="de">
            <body>
                <MantineProvider>{children}</MantineProvider>
            </body>
        </html>
    );
}
